In [3]:
import numpy as np # type: ignore
# 1-D Array
x = np.arange(1,11)
print(x[2])
print(x[9])
print(x[-3])
print(x[1:5])
print(x+2)
print(x*2)

3
10
8
[2 3 4 5]
[ 3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12 14 16 18 20]


In [1]:
import numpy as np
# 2-D Array
x = np.arange(1,10).reshape(3,3)
print(x)
print(x+2)
print(x*2)
print(x[2][2])
print(x[1][2])
print(x[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
9
6
5


In [41]:
import numpy as np
# 3-D Array
x = np.arange(1,13).reshape(2,3,2)
print(x)
print(x[0][1][1])
print(x[1][1][1])
print(x[0][2][1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
4
10
6


In [4]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
print(x)
print(y)
z=np.concatenate((x,y),axis=1) #will concatenate column wise
a=np.concatenate((x,y),axis=0) #will concatenate row wise
print(z)
print(a)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
import numpy as np
x = np.arange(1,9).reshape(2,2,2)
for i in np.nditer(x):
    print(i)
print(x)

1
2
3
4
5
6
7
8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# Create 3*3 array from range 10 to 19
# print third column from all rows
# print odd rows and even columns from above array
# find max and min from axix=0 and axix=1

import numpy as np
x = np.arange(1,10).reshape(3,3)
l = np.arange(1,10).reshape(3,3) 
print(x)
print(x[0:,2:])
print(x[0::2,1:2])
Max = np.max(x,axis=0)
Min = np.min(x,axis=1)
y = np.where(l>5,"Cdnndndf",l)
print(y)
print(Max)
print(Min)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]
[[2]
 [8]]
[['1' '2' '3']
 ['4' '5' 'Cdnndndf']
 ['Cdnndndf' 'Cdnndndf' 'Cdnndndf']]
[7 8 9]
[1 4 7]
